<?php namespace Anomaly\Streams\Platform\Model\Contacts;

use Anomaly\Streams\Platform\Entry\EntryModel;

class ContactsContactsEntryModel extends EntryModel
{

    

    protected $searchable = false;

    protected $table = 'contacts_contacts';

    protected $titleName = 'name';

    protected $rules = [
'company' => 'required',
'publish' => 'required',
'division' => 'required',
'address' => 'required',
'phone' => 'required',
'fax' => 'required',
'company_email' => 'required',
'sales_name' => 'required',
'photo' => 'required',
'mobile01' => 'required',
'mobile02' => 'required',
'personal_email' => 'required',
'biodata' => 'required',
'note' => 'required',
];

    protected $fields = [
'company',
'publish',
'division',
'address',
'phone',
'fax',
'company_email',
'sales_name',
'photo',
'mobile01',
'mobile02',
'personal_email',
'biodata',
'note',
];

    protected $dates = ['created_at', 'updated_at'];

    protected $relationships = ['photo'];

    

    

    

    protected $stream = [
'id' => '49',
'namespace' => 'contacts',
'slug' => 'contacts',
'prefix' => 'contacts_',
'title_column' => 'name',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '0',
'searchable' => '0',
'trashable' => '0',
'translatable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 238,
'sort_order' => 173,
'stream_id' => 49,
'field_id' => 175,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '175',
'namespace' => 'contacts',
'slug' => 'company',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 177,
'field_id' => 175,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.company.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.company.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.company.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.company.instructions',
],
],
],
'translations' => [
[
'id' => 242,
'assignment_id' => 238,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.company.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.company.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.company.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.company.instructions.contacts',
],
],
],
[
'id' => 239,
'sort_order' => 174,
'stream_id' => 49,
'field_id' => 176,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '176',
'namespace' => 'contacts',
'slug' => 'publish',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:2:{s:13:"default_value";b:1;s:4:"mode";s:5:"radio";}',
'locked' => '1',
'translations' => [
[
'id' => 178,
'field_id' => 176,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.publish.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.publish.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.publish.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.publish.instructions',
],
],
],
'translations' => [
[
'id' => 243,
'assignment_id' => 239,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.publish.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.publish.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.publish.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.publish.instructions.contacts',
],
],
],
[
'id' => 240,
'sort_order' => 175,
'stream_id' => 49,
'field_id' => 177,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '177',
'namespace' => 'contacts',
'slug' => 'division',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 179,
'field_id' => 177,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.division.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.division.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.division.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.division.instructions',
],
],
],
'translations' => [
[
'id' => 244,
'assignment_id' => 240,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.division.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.division.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.division.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.division.instructions.contacts',
],
],
],
[
'id' => 241,
'sort_order' => 176,
'stream_id' => 49,
'field_id' => 178,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '178',
'namespace' => 'contacts',
'slug' => 'address',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 180,
'field_id' => 178,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.address.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.address.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.address.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.address.instructions',
],
],
],
'translations' => [
[
'id' => 245,
'assignment_id' => 241,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.address.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.address.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.address.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.address.instructions.contacts',
],
],
],
[
'id' => 242,
'sort_order' => 177,
'stream_id' => 49,
'field_id' => 179,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '179',
'namespace' => 'contacts',
'slug' => 'phone',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 181,
'field_id' => 179,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.phone.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.phone.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.phone.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.phone.instructions',
],
],
],
'translations' => [
[
'id' => 246,
'assignment_id' => 242,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.phone.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.phone.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.phone.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.phone.instructions.contacts',
],
],
],
[
'id' => 243,
'sort_order' => 178,
'stream_id' => 49,
'field_id' => 180,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '180',
'namespace' => 'contacts',
'slug' => 'fax',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 182,
'field_id' => 180,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.fax.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.fax.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.fax.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.fax.instructions',
],
],
],
'translations' => [
[
'id' => 247,
'assignment_id' => 243,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.fax.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.fax.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.fax.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.fax.instructions.contacts',
],
],
],
[
'id' => 244,
'sort_order' => 179,
'stream_id' => 49,
'field_id' => 181,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '181',
'namespace' => 'contacts',
'slug' => 'company_email',
'type' => 'anomaly.field_type.email',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 183,
'field_id' => 181,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.company_email.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.company_email.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.company_email.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.company_email.instructions',
],
],
],
'translations' => [
[
'id' => 248,
'assignment_id' => 244,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.company_email.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.company_email.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.company_email.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.company_email.instructions.contacts',
],
],
],
[
'id' => 245,
'sort_order' => 180,
'stream_id' => 49,
'field_id' => 182,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '182',
'namespace' => 'contacts',
'slug' => 'sales_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 184,
'field_id' => 182,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.sales_name.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.sales_name.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.sales_name.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.sales_name.instructions',
],
],
],
'translations' => [
[
'id' => 249,
'assignment_id' => 245,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.sales_name.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.sales_name.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.sales_name.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.sales_name.instructions.contacts',
],
],
],
[
'id' => 246,
'sort_order' => 181,
'stream_id' => 49,
'field_id' => 183,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '183',
'namespace' => 'contacts',
'slug' => 'photo',
'type' => 'anomaly.field_type.file',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 185,
'field_id' => 183,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.photo.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.photo.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.photo.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.photo.instructions',
],
],
],
'translations' => [
[
'id' => 250,
'assignment_id' => 246,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.photo.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.photo.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.photo.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.photo.instructions.contacts',
],
],
],
[
'id' => 247,
'sort_order' => 182,
'stream_id' => 49,
'field_id' => 184,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '184',
'namespace' => 'contacts',
'slug' => 'mobile01',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 186,
'field_id' => 184,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.mobile01.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.mobile01.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.mobile01.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.mobile01.instructions',
],
],
],
'translations' => [
[
'id' => 251,
'assignment_id' => 247,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.mobile01.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.mobile01.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.mobile01.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.mobile01.instructions.contacts',
],
],
],
[
'id' => 248,
'sort_order' => 183,
'stream_id' => 49,
'field_id' => 185,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '185',
'namespace' => 'contacts',
'slug' => 'mobile02',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 187,
'field_id' => 185,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.mobile02.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.mobile02.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.mobile02.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.mobile02.instructions',
],
],
],
'translations' => [
[
'id' => 252,
'assignment_id' => 248,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.mobile02.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.mobile02.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.mobile02.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.mobile02.instructions.contacts',
],
],
],
[
'id' => 249,
'sort_order' => 184,
'stream_id' => 49,
'field_id' => 186,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '186',
'namespace' => 'contacts',
'slug' => 'personal_email',
'type' => 'anomaly.field_type.email',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 188,
'field_id' => 186,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.personal_email.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.personal_email.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.personal_email.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.personal_email.instructions',
],
],
],
'translations' => [
[
'id' => 253,
'assignment_id' => 249,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.personal_email.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.personal_email.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.personal_email.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.personal_email.instructions.contacts',
],
],
],
[
'id' => 250,
'sort_order' => 185,
'stream_id' => 49,
'field_id' => 187,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '187',
'namespace' => 'contacts',
'slug' => 'biodata',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 189,
'field_id' => 187,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.biodata.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.biodata.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.biodata.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.biodata.instructions',
],
],
],
'translations' => [
[
'id' => 254,
'assignment_id' => 250,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.biodata.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.biodata.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.biodata.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.biodata.instructions.contacts',
],
],
],
[
'id' => 251,
'sort_order' => 186,
'stream_id' => 49,
'field_id' => 188,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'translatable' => 0,
'field' => [
'id' => '188',
'namespace' => 'contacts',
'slug' => 'note',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 190,
'field_id' => 188,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::field.note.name',
'placeholder' => 'toyotadjakarta.module.contacts::field.note.placeholder',
'warning' => 'toyotadjakarta.module.contacts::field.note.warning',
'instructions' => 'toyotadjakarta.module.contacts::field.note.instructions',
],
],
],
'translations' => [
[
'id' => 255,
'assignment_id' => 251,
'locale' => 'en',
'label' => 'toyotadjakarta.module.contacts::field.note.label.contacts',
'warning' => 'toyotadjakarta.module.contacts::field.note.warning.contacts',
'placeholder' => 'toyotadjakarta.module.contacts::field.note.placeholder.contacts',
'instructions' => 'toyotadjakarta.module.contacts::field.note.instructions.contacts',
],
],
],
],
'translations' => [
[
'id' => 49,
'stream_id' => 49,
'locale' => 'en',
'name' => 'toyotadjakarta.module.contacts::stream.contacts.name',
'description' => 'toyotadjakarta.module.contacts::stream.contacts.description',
],
],
];

    
public function photo()
{

return $this->getFieldType('photo')->getRelation();
}

}
